const PRIVACY_POLICY_VERSION = '2026-09-27';
const REGISTRATION_PRIVACY_CONSENT_TYPE = 'registration_privacy';
const PUBLIC_REGISTRATION_CONSENT_SOURCE = 'public_registration';

module.exports = {
  PRIVACY_POLICY_VERSION,
  REGISTRATION_PRIVACY_CONSENT_TYPE,
  PUBLIC_REGISTRATION_CONSENT_SOURCE
};